# Generated by Django 5.1.5 on 2026-09-25 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_registration(apps, schema_editor):
    """Points every existing attendance row at the registration behind its
    participation, so re-keying loses nothing."""
    Attendance = apps.get_model('attendance', 'Attendance')
    for attendance in Attendance.objects.select_related('participation').filter(registration__isnull=True):
        if attendance.participation_id:
            attendance.registration_id = attendance.participation.registration_id
            attendance.save(update_fields=['registration'])


def clear_registration(apps, schema_editor):
    Attendance = apps.get_model('attendance', 'Attendance')
    Attendance.objects.update(registration=None)


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_reviewed_by_alter_attendance_status'),
        ('participation', '0003_delete_participationcapture'),
        ('registrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_manual',
            field=models.BooleanField(default=False, help_text='True when the Event Coordinator recorded this directly rather than deciding a Faculty request. Attendance is never inferred from a registration or a capture.'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='registration',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance', to='registrations.registration'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='participation',
            field=models.OneToOneField(blank=True, help_text='Null when the student never submitted a live capture.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance', to='participation.participation'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='requested_by',
            field=models.ForeignKey(blank=True, help_text='The Faculty member who requested attendance. Null for a record the Event Coordinator marked directly, which has no requester. Never client-supplied.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_registration, clear_registration),
    ]
