# Generated by Django 5.1.5 on 2026-09-14 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('REGISTRATION_SUBMITTED', 'Registration Submitted'), ('REGISTRATION_APPROVED', 'Registration Approved'), ('REGISTRATION_REJECTED', 'Registration Rejected'), ('EVENT_PUBLISHED', 'Event Published'), ('EVENT_CANCELLED', 'Event Cancelled'), ('PARTICIPATION_SUBMITTED', 'Participation Submitted'), ('EVIDENCE_VERIFIED', 'Evidence Verified'), ('EVIDENCE_REJECTED', 'Evidence Rejected'), ('EVIDENCE_RESUBMISSION_REQUIRED', 'Evidence Resubmission Required'), ('HOD_OVERRIDE', 'HOD Override'), ('ATTENDANCE_REQUESTED', 'Attendance Requested'), ('ATTENDANCE_APPROVED', 'Attendance Approved'), ('ATTENDANCE_REJECTED', 'Attendance Rejected'), ('OD_REQUESTED', 'OD Requested'), ('OD_APPROVED', 'OD Approved'), ('OD_REJECTED', 'OD Rejected'), ('ACHIEVEMENT_CREATED', 'Achievement Created'), ('ACHIEVEMENT_APPROVED', 'Achievement Approved'), ('ACHIEVEMENT_REJECTED', 'Achievement Rejected')], max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('related_entity_type', models.CharField(blank=True, default='', help_text="Lowercase model name, e.g. 'attendance', 'evidence'. Informational only — it grants no access; the target endpoint re-authorizes independently.", max_length=40)),
                ('related_entity_id', models.PositiveIntegerField(blank=True, null=True)),
                ('action_route', models.CharField(blank=True, default='', help_text='An INTERNAL Angular route path such as "/student/attendance". Constrained by a DB CheckConstraint to start with "/" and by the service layer to reject "//" and any scheme, so a stored value can never become an external redirect.', max_length=200)),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('HIGH', 'High')], default='NORMAL', max_length=10)),
                ('dedupe_key', models.CharField(blank=True, default='', help_text='Optional idempotency key. When set it is unique, so a retried or double-clicked business action reuses the existing row instead of creating a duplicate. Left blank for notifications that may legitimately recur.', max_length=200)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(help_text='Server-selected from the business object. Never accepted from client input.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notif_recipient_created_idx'), models.Index(fields=['recipient', 'is_read'], name='notif_recipient_unread_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('dedupe_key',), name='unique_notification_dedupe_key'), models.CheckConstraint(condition=models.Q(models.Q(('is_read', True), ('read_at__isnull', False)), models.Q(('is_read', False), ('read_at__isnull', True)), _connector='OR'), name='notification_read_at_matches_is_read'), models.CheckConstraint(condition=models.Q(('action_route', ''), models.Q(('action_route__startswith', '/'), models.Q(('action_route__startswith', '//'), _negated=True)), _connector='OR'), name='notification_action_route_is_internal')],
            },
        ),
    ]
