# Generated by Django 5.1.5 on 2026-09-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_hod_override_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('REGISTRATION_SUBMITTED', 'Registration Submitted'), ('REGISTRATION_APPROVED', 'Registration Approved'), ('REGISTRATION_REJECTED', 'Registration Rejected'), ('EVENT_PUBLISHED', 'Event Published'), ('EVENT_CANCELLED', 'Event Cancelled'), ('PARTICIPATION_SUBMITTED', 'Participation Submitted'), ('EVIDENCE_VERIFIED', 'Evidence Verified'), ('EVIDENCE_REJECTED', 'Evidence Rejected'), ('EVIDENCE_RESUBMISSION_REQUIRED', 'Evidence Resubmission Required'), ('EVENT_COORDINATOR_OVERRIDE', 'Event Coordinator Override'), ('ATTENDANCE_REQUESTED', 'Attendance Requested'), ('ATTENDANCE_APPROVED', 'Attendance Approved'), ('ATTENDANCE_REJECTED', 'Attendance Rejected'), ('OD_REQUESTED', 'OD Requested'), ('OD_APPROVED', 'OD Approved'), ('OD_REJECTED', 'OD Rejected'), ('ACHIEVEMENT_CREATED', 'Achievement Created'), ('ACHIEVEMENT_APPROVED', 'Achievement Approved'), ('ACHIEVEMENT_REJECTED', 'Achievement Rejected')], max_length=40),
        ),
    ]
