# Generated by Django 5.1.5 on 2026-09-13 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0001_initial'),
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('event_date', models.DateField()),
                ('venue', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
                ('registration_start_date', models.DateField()),
                ('registration_end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conducting_college', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='colleges.college')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, help_text='Internal HOD-authorization scope. Not user-facing; null means system-wide (Admin-managed).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='departments.department')),
            ],
            options={
                'ordering': ['-event_date'],
                'indexes': [models.Index(fields=['status'], name='events_even_status_5709b6_idx'), models.Index(fields=['event_date'], name='events_even_event_d_2c2da5_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('registration_end_date__lt', models.F('event_date'))), name='registration_end_before_event_date'), models.CheckConstraint(condition=models.Q(('registration_start_date__lte', models.F('registration_end_date'))), name='registration_start_before_or_equal_end')],
            },
        ),
    ]
