# Generated by Django 5.1.5 on 2026-09-25 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('events', '0002_event_venue_latitude_event_venue_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Internal Event Coordinator-authorization scope. Not user-facing; null means system-wide (Admin-managed).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='departments.department'),
        ),
    ]
