# Generated by Django 5.1.5 on 2026-09-13 17:55

import apps.verification.models
import django.core.files.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('RESUBMISSION_REQUIRED', 'Resubmission Required')], default='SUBMITTED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='participation.participation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('submission_reason', models.TextField(blank=True, default='', help_text='Set for version 2+: a copy of the Faculty resubmission-request reason that triggered it.')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='verification.evidence')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['version_number'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('RESUBMISSION_REQUIRED', 'Resubmission Required')], max_length=30)),
                ('reason', models.TextField(blank=True, default='')),
                ('is_hod_override', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('evidence_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verifications', to='verification.evidenceversion')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capture_role', models.CharField(choices=[('PRIMARY', 'Primary'), ('ADDITIONAL', 'Additional')], max_length=20)),
                ('object_reference', models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url=None, location='D:\\Smart_Students_Event_Attendace\\backend\\media\\participation_captures'), upload_to=apps.verification.models.capture_upload_path)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveIntegerField()),
                ('sha256_hash', models.CharField(db_index=True, max_length=64)),
                ('device_capture_timestamp', models.DateTimeField(help_text='Client-reported capture time. Evidence metadata, not a trusted security value.')),
                ('server_received_timestamp', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('gps_accuracy', models.FloatField(help_text='Meters, as reported by the browser Geolocation API.')),
                ('venue_distance', models.FloatField(blank=True, help_text='Meters from the event venue, when venue coordinates are configured.', null=True)),
                ('location_warning', models.BooleanField(default=False, help_text='True when venue_distance exceeds VENUE_WARNING_DISTANCE_METERS. Never blocks submission.')),
                ('validation_status', models.CharField(choices=[('VALID', 'Valid')], default='VALID', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evidence_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captures', to='verification.evidenceversion')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='evidence',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='verification.evidenceversion'),
        ),
        migrations.AddConstraint(
            model_name='evidenceversion',
            constraint=models.UniqueConstraint(fields=('evidence', 'version_number'), name='unique_version_number_per_evidence'),
        ),
        migrations.AddConstraint(
            model_name='evidenceverification',
            constraint=models.CheckConstraint(condition=models.Q(('decision', 'VERIFIED'), models.Q(('reason', ''), _negated=True), _connector='OR'), name='reason_required_for_reject_or_resubmission'),
        ),
        migrations.AddConstraint(
            model_name='evidencecapture',
            constraint=models.UniqueConstraint(condition=models.Q(('capture_role', 'PRIMARY')), fields=('evidence_version',), name='unique_primary_capture_per_evidence_version'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['status'], name='verificatio_status_46e961_idx'),
        ),
    ]
