# Generated by Django 5.1.5 on 2026-09-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0003_rename_hod_override_to_event_coordinator_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencecapture',
            name='address_precision',
            field=models.CharField(choices=[('EXACT', 'Exact'), ('APPROXIMATE', 'Approximate'), ('UNRESOLVED', 'Unresolved')], default='UNRESOLVED', help_text='EXACT only when the provider placed this at a specific building AND the GPS accuracy was good enough for that to mean anything.', max_length=20),
        ),
        migrations.AddField(
            model_name='evidencecapture',
            name='address_provider',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='evidencecapture',
            name='address_resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidencecapture',
            name='resolved_address',
            field=models.TextField(blank=True, default='', help_text='Reverse-geocoded address. Blank when it could not be resolved.'),
        ),
    ]
