# Generated by Django 5.1.5 on 2026-09-14 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participation', '0003_delete_participationcapture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('achievement_type', models.CharField(help_text='Free text, consistent with the free-text Event.category convention.', max_length=100)),
                ('achievement_date', models.DateField(help_text='Must not predate the event, and must not be in the future — see services.validate_achievement_date.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Server-set from request.user. Never client-supplied.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achievements', to='participation.participation')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='The HOD/Admin who approved or rejected. Server-set, never client-supplied.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-achievement_date', '-created_at'],
                'indexes': [models.Index(fields=['status'], name='achievement_status_72d1c6_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('status', 'REJECTED'), _negated=True), models.Q(('rejection_reason', ''), _negated=True), _connector='OR'), name='achievement_rejection_reason_required'), models.CheckConstraint(condition=models.Q(models.Q(('reviewed_at__isnull', True), ('reviewed_by__isnull', True), ('status__in', ['DRAFT', 'PENDING_APPROVAL'])), models.Q(('status__in', ['APPROVED', 'REJECTED']), ('reviewed_at__isnull', False), ('reviewed_by__isnull', False)), _connector='OR'), name='achievement_review_fields_match_status')],
            },
        ),
    ]
