# Generated by Django 5.1.5 on 2026-09-25 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='The Event Coordinator/Admin who approved or rejected. Server-set, never client-supplied.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
