# Generated by Django 5.1.5 on 2026-09-25 14:45

import apps.certificates.models
import django.core.files.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participation', '0003_delete_participationcapture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(help_text='1-based, server-derived. Never accepted from the client.')),
                ('object_reference', models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url=None, location='D:\\Smart_Students_Event_Attendace\\backend\\media\\certificates'), upload_to=apps.certificates.models.certificate_upload_path)),
                ('original_filename', models.CharField(blank=True, default='', help_text='Shown to reviewers for recognition only. Never used to build a storage path.', max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveIntegerField()),
                ('sha256_hash', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('ACCEPTED_BY_COORDINATOR', 'Accepted by Event Coordinator')], default='SUBMITTED', max_length=30)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='participation.participation')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='The Faculty member who decided, or the Event Coordinator who accepted. Server-set.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['participation_id', 'attempt_number'],
                'indexes': [models.Index(fields=['status'], name='certificate_status_31e804_idx')],
                'constraints': [models.UniqueConstraint(fields=('participation', 'attempt_number'), name='unique_certificate_attempt_per_participation'), models.CheckConstraint(condition=models.Q(('attempt_number__gte', 1), ('attempt_number__lte', 3)), name='certificate_attempt_number_within_limit'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'REJECTED'), _negated=True), models.Q(('rejection_reason', ''), _negated=True), _connector='OR'), name='certificate_rejection_reason_required')],
            },
        ),
    ]
