# Generated by Django 5.1.5 on 2026-09-26 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
        ('participation', '0003_delete_participationcapture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='final_decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='final_decided_by',
            field=models.ForeignKey(blank=True, help_text='The Event Coordinator who made the final decision. Server-set.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificate',
            name='final_decision',
            field=models.CharField(blank=True, choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='', help_text='Blank until the Event Coordinator has made the final decision.', max_length=20),
        ),
        migrations.AddField(
            model_name='certificate',
            name='final_rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('final_decision', 'REJECTED'), _negated=True), models.Q(('final_rejection_reason', ''), _negated=True), _connector='OR'), name='certificate_final_rejection_reason_required'),
        ),
    ]
