# Generated by Django 5.1.5 on 2026-09-13 14:11

import apps.participation.models
import django.core.files.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_event_venue_latitude_event_venue_longitude'),
        ('registrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('PENDING_VERIFICATION', 'Pending Verification')], default='DRAFT', max_length=30)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participations', to='events.event')),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='participation', to='registrations.registration')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParticipationCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PRIMARY', 'Primary'), ('ADDITIONAL', 'Additional')], max_length=20)),
                ('image', models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url=None, location='D:\\Smart_Students_Event_Attendace\\backend\\media\\participation_captures'), upload_to=apps.participation.models.capture_upload_path)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveIntegerField()),
                ('sha256_hash', models.CharField(db_index=True, max_length=64)),
                ('device_capture_timestamp', models.DateTimeField(help_text='Client-reported capture time. Evidence metadata, not a trusted security value.')),
                ('server_received_timestamp', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('gps_accuracy', models.FloatField(help_text='Meters, as reported by the browser Geolocation API.')),
                ('venue_distance', models.FloatField(blank=True, help_text='Meters from the event venue, when venue coordinates are configured.', null=True)),
                ('location_warning', models.BooleanField(default=False, help_text='True when venue_distance exceeds VENUE_WARNING_DISTANCE_METERS. Never blocks submission.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captures', to='participation.participation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='participation',
            index=models.Index(fields=['status'], name='participati_status_d24e80_idx'),
        ),
        migrations.AddConstraint(
            model_name='participationcapture',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'PRIMARY')), fields=('participation',), name='unique_primary_capture_per_participation'),
        ),
    ]
