# Generated by Django 5.1.5 on 2026-09-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation',
            name='verified_at',
        ),
        migrations.AlterField(
            model_name='participation',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted')], default='DRAFT', max_length=30),
        ),
        # ParticipationCapture itself is deleted in 0003_delete_participationcapture,
        # AFTER apps.verification's data migration (0002) has copied every row into
        # Evidence/EvidenceVersion/EvidenceCapture — see that migration's docstring.
    ]
