# Generated by Django 5.1.5 on 2026-09-13 12:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('STUDENT', 'Student'), ('FACULTY', 'Faculty'), ('HOD', 'HOD'), ('ADMIN', 'Admin')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='departments.department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'This username is already taken.'}, help_text='Required. Lowercase letters and numbers only.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Username must contain lowercase letters and numbers only.', regex='^[a-z0-9]+$')]),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('role', 'HOD')), fields=('department',), name='unique_active_hod_per_department'),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registration_requests', to='departments.department'),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_registration_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_request', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='registrationrequest',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['STUDENT', 'FACULTY'])), name='registration_request_role_must_be_student_or_faculty'),
        ),
    ]
