# Generated by Django 5.1.5 on 2026-09-25 14:24

from django.db import migrations, models


def backfill_full_name(apps, schema_editor):
    """Carries the existing first/last name pair over into the new single
    field, so no existing account loses the name it already had."""
    User = apps.get_model('accounts', 'User')
    for user in User.objects.exclude(first_name='', last_name='').only('id', 'first_name', 'last_name'):
        user.full_name = f'{user.first_name} {user.last_name}'.strip()
        user.save(update_fields=['full_name'])


def clear_full_name(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.update(full_name='')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_hod_becomes_event_coordinator'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='faculty_id',
            field=models.CharField(blank=True, help_text='Faculty only. The identifier issued by the college.', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, default='', help_text="The person's full name as the institution records it.", max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='university_registration_number',
            field=models.CharField(blank=True, help_text='Student only. USN, UUCMS number, or university registration number.', max_length=50, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('role', 'STUDENT'), ('university_registration_number__isnull', True), _connector='OR'), name='university_registration_number_is_student_only'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('role', 'FACULTY'), ('faculty_id__isnull', True), _connector='OR'), name='faculty_id_is_faculty_only'),
        ),
        migrations.RunPython(backfill_full_name, clear_full_name),
    ]
