# Generated by Django 5.1.5 on 2026-09-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_faculty_id_user_full_name_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='faculty_id_is_faculty_only',
        ),
        migrations.AlterField(
            model_name='user',
            name='faculty_id',
            field=models.CharField(blank=True, help_text='Faculty and Event Coordinator. The identifier issued by the college. Unique across both roles: an Event Coordinator is a faculty member, so the same person must not be able to hold two identities by changing role.', max_length=50, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['FACULTY', 'EVENT_COORDINATOR']), ('faculty_id__isnull', True), _connector='OR'), name='faculty_id_is_faculty_or_coordinator'),
        ),
    ]
