# Generated by Django 5.1.5 on 2026-09-14 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participation', '0003_delete_participationcapture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ODRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Why on-duty is being requested — the justification the HOD reviews. Required.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending HOD Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='od_request', to='participation.participation')),
                ('requested_by', models.ForeignKey(help_text='The Faculty member who requested OD. Never client-supplied.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='The HOD/Admin who approved or rejected. Server-set from request.user, never client-supplied.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status'], name='od_odreques_status_ee478d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='od_reason_required'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'REJECTED'), _negated=True), models.Q(('rejection_reason', ''), _negated=True), _connector='OR'), name='od_rejection_reason_required'), models.CheckConstraint(condition=models.Q(models.Q(('reviewed_at__isnull', True), ('reviewed_by__isnull', True), ('status', 'PENDING')), models.Q(models.Q(('status', 'PENDING'), _negated=True), ('reviewed_at__isnull', False), ('reviewed_by__isnull', False)), _connector='OR'), name='od_review_fields_match_status')],
            },
        ),
    ]
