# Generated by Django 5.1.5 on 2026-09-25 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('od', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='odrequest',
            name='reason',
            field=models.TextField(help_text='Why on-duty is being requested — the justification the Event Coordinator reviews. Required.'),
        ),
        migrations.AlterField(
            model_name='odrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='The Event Coordinator/Admin who approved or rejected. Server-set from request.user, never client-supplied.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='odrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Event Coordinator Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
