"""
Report renderers: CSV, XLSX and PDF.

All three render **entirely in memory** and return bytes. Nothing is written to
disk, so no report ever lands in MEDIA_ROOT or any other publicly reachable
location, and there is no temporary file to leak or clean up.

An empty dataset is a valid report in every format: CSV and XLSX still carry
their header row, and the PDF says so in words. None of them raises.
"""

import csv
import io
import re

from django.utils import timezone

CONTENT_TYPES = {
    'csv': 'text/csv; charset=utf-8',
    'xlsx': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'pdf': 'application/pdf',
}

_UNSAFE_FILENAME = re.compile(r'[^A-Za-z0-9._-]+')


def build_filename(definition, fmt: str) -> str:
    """A safe, predictable download name.

    Built only from the allowlisted report key and a timestamp — never from
    user input — and then stripped of anything outside `[A-Za-z0-9._-]`, so it
    cannot carry a path separator, a directory traversal sequence, a quote that
    would break the Content-Disposition header, or any token/secret.
    """
    stamp = timezone.localtime().strftime('%Y%m%d-%H%M%S')
    raw = f'{definition.key}-{stamp}.{fmt}'
    return _UNSAFE_FILENAME.sub('-', raw)


def _meta_lines(dataset, *, user, filter_summary):
    return [
        f'Report: {dataset.title}',
        f'Generated: {timezone.localtime().strftime("%Y-%m-%d %H:%M %Z")}',
        f'Generated by: {user.username} ({user.role})',
        f'Filters: {filter_summary}',
        f'Rows: {len(dataset.rows)}',
    ]


# ------------------------------------------------------------------- CSV --

def render_csv(dataset, *, user, filter_summary) -> bytes:
    """UTF-8 with a BOM so Excel opens non-ASCII names correctly, `\r\n` line
    endings per RFC 4180, and a stable column order taken from the dataset."""
    buffer = io.StringIO()
    writer = csv.writer(buffer, lineterminator='\r\n')
    writer.writerow(dataset.columns)
    for row in dataset.rows:
        writer.writerow(['' if value is None else value for value in row])
    return buffer.getvalue().encode('utf-8-sig')


# ------------------------------------------------------------------ XLSX --

def render_xlsx(dataset, *, user, filter_summary) -> bytes:
    from openpyxl import Workbook
    from openpyxl.styles import Alignment, Font
    from openpyxl.utils import get_column_letter

    workbook = Workbook()
    sheet = workbook.active
    sheet.title = _sheet_name(dataset.title)

    header_font = Font(bold=True)
    sheet.append(dataset.columns)
    for cell in sheet[1]:
        cell.font = header_font
        cell.alignment = Alignment(vertical='center')

    for row in dataset.rows:
        sheet.append(['' if value is None else value for value in row])

    # Readable widths, bounded so one long title cannot make a column unusable.
    for index, column in enumerate(dataset.columns, start=1):
        longest = len(str(column))
        for row in dataset.rows:
            if index - 1 < len(row):
                longest = max(longest, len(str(row[index - 1] if row[index - 1] is not None else '')))
        sheet.column_dimensions[get_column_letter(index)].width = min(max(longest + 2, 10), 50)

    sheet.freeze_panes = 'A2'

    # Provenance on a separate sheet so it can never be mistaken for data or
    # break a formula on the data sheet.
    meta = workbook.create_sheet('Report Info')
    for line in _meta_lines(dataset, user=user, filter_summary=filter_summary):
        label, _, value = line.partition(': ')
        meta.append([label, value])
    if dataset.description:
        meta.append(['Note', dataset.description])
    meta.column_dimensions['A'].width = 18
    meta.column_dimensions['B'].width = 70

    stream = io.BytesIO()
    workbook.save(stream)
    return stream.getvalue()


def _sheet_name(title: str) -> str:
    """Excel forbids : \\ / ? * [ ] and caps sheet names at 31 characters."""
    cleaned = re.sub(r'[:\\/?*\[\]]', '-', title)
    return cleaned[:31] or 'Report'


# ------------------------------------------------------------------- PDF --

def render_pdf(dataset, *, user, filter_summary) -> bytes:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4, landscape
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.lib.units import mm
    from reportlab.platypus import (
        Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle,
    )

    stream = io.BytesIO()
    # Landscape: these reports are wide, and portrait would clip columns.
    document = SimpleDocTemplate(
        stream, pagesize=landscape(A4),
        leftMargin=12 * mm, rightMargin=12 * mm, topMargin=12 * mm, bottomMargin=12 * mm,
        title=dataset.title, author='SEAMS-AI',
    )
    styles = getSampleStyleSheet()
    cell_style = styles['BodyText'].clone('cell')
    cell_style.fontSize = 7
    cell_style.leading = 9

    story = [Paragraph(dataset.title, styles['Title'])]
    for line in _meta_lines(dataset, user=user, filter_summary=filter_summary):
        story.append(Paragraph(_escape(line), styles['Normal']))
    if dataset.description:
        story.append(Spacer(1, 3 * mm))
        story.append(Paragraph(_escape(dataset.description), styles['Italic']))
    story.append(Spacer(1, 5 * mm))

    if dataset.is_empty:
        story.append(Paragraph('No records match the selected filters.', styles['Heading3']))
    else:
        # Every cell is a Paragraph so long values wrap instead of overflowing
        # the page, and repeatRows=1 repeats the header on each page.
        header = [Paragraph(f'<b>{_escape(str(c))}</b>', cell_style) for c in dataset.columns]
        body = [
            [Paragraph(_escape('' if value is None else str(value)), cell_style) for value in row]
            for row in dataset.rows
        ]
        table = Table([header] + body, repeatRows=1, hAlign='LEFT')
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#e9ecef')),
            ('GRID', (0, 0), (-1, -1), 0.4, colors.HexColor('#adb5bd')),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f8f9fa')]),
            ('LEFTPADDING', (0, 0), (-1, -1), 3),
            ('RIGHTPADDING', (0, 0), (-1, -1), 3),
        ]))
        story.append(table)

    document.build(story)
    return stream.getvalue()


def _escape(text: str) -> str:
    """ReportLab parses a mini-HTML in Paragraph text, so raw data must be
    escaped or an ampersand or angle bracket in a title would break the build."""
    return (
        str(text).replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
    )


RENDERERS = {'csv': render_csv, 'xlsx': render_xlsx, 'pdf': render_pdf}


def render(dataset, *, fmt: str, user, filter_summary) -> bytes:
    return RENDERERS[fmt](dataset, user=user, filter_summary=filter_summary)
