"""
Report authorization, generation, format validity and content security
(§36, §37, §38, §41).

Format tests parse the generated bytes back — CSV through `csv`, XLSX through
`openpyxl`, PDF through `pypdf` — rather than accepting HTTP 200 as proof.
"""

import csv
import io
from unittest import mock

from django.urls import reverse
from rest_framework import status
from rest_framework.test import APITestCase

from apps.analytics.tests.helpers import AuthMixin, build_world
from apps.audit.models import AuditLog
from apps.reports import registry


def parse_csv(content: bytes):
    return list(csv.reader(io.StringIO(content.decode('utf-8-sig'))))


def parse_xlsx(content: bytes):
    from openpyxl import load_workbook
    return load_workbook(io.BytesIO(content))


def pdf_text(content: bytes) -> str:
    from pypdf import PdfReader
    return ''.join(page.extract_text() or '' for page in PdfReader(io.BytesIO(content)).pages)


class ReportCatalogueTests(AuthMixin, APITestCase):
    def setUp(self):
        self.w = build_world()
        self.url = reverse('report-types')

    def test_listing_requires_authentication(self):
        self.client.credentials()
        self.assertEqual(self.client.get(self.url).status_code, status.HTTP_401_UNAUTHORIZED)

    def test_each_role_is_offered_only_its_own_report_types(self):
        self._auth_as('studenta')
        student_keys = {r['key'] for r in self.client.get(self.url).data}
        self._auth_as('facultycs')
        faculty_keys = {r['key'] for r in self.client.get(self.url).data}
        self._auth_as('hodcs')
        event_coordinator_keys = {r['key'] for r in self.client.get(self.url).data}
        self._auth_as('sysadmin')
        admin_keys = {r['key'] for r in self.client.get(self.url).data}

        self.assertNotIn('system', student_keys)
        self.assertNotIn('department', student_keys)
        self.assertNotIn('system', faculty_keys)
        self.assertNotIn('department', faculty_keys)
        self.assertIn('department', event_coordinator_keys)
        self.assertNotIn('system', event_coordinator_keys)
        self.assertIn('system', admin_keys)
        # Admin is offered every registered type; asserted against the
        # registry rather than a literal, so adding a report cannot make
        # this quietly wrong.
        self.assertEqual(admin_keys, set(registry.REPORTS))

    def test_every_registered_report_is_complete_and_role_scoped(self):
        # The count is deliberately not asserted: it changed when certificates
        # arrived, and would change again. What must hold for every report is
        # that it has a builder, a description, and at least one role that may
        # run it.
        self.assertGreaterEqual(len(registry.REPORTS), 12)
        for key, definition in registry.REPORTS.items():
            self.assertTrue(definition.builder_name, key)
            self.assertTrue(definition.description, key)
            self.assertTrue(definition.roles, key)

    def test_the_certificate_and_tracking_reports_are_registered(self):
        self.assertIn('certificate', registry.REPORTS)
        self.assertIn('event-tracking', registry.REPORTS)
        # Tracking carries other students' records, so it is staff-only.
        self.assertNotIn(registry.STUDENT, registry.REPORTS['event-tracking'].roles)


class ReportAuthorizationTests(AuthMixin, APITestCase):
    def setUp(self):
        self.w = build_world()

    def _export(self, report_type, fmt='csv', params=None):
        return self.client.get(
            reverse('report-export', args=[report_type]), {'file_format': fmt, **(params or {})},
        )

    def test_export_requires_authentication(self):
        self.client.credentials()
        self.assertEqual(self._export('student-participation').status_code,
                         status.HTTP_401_UNAUTHORIZED)

    def test_student_cannot_export_the_system_report(self):
        self._auth_as('studenta')
        self.assertEqual(self._export('system').status_code, status.HTTP_403_FORBIDDEN)

    def test_student_cannot_export_the_department_report(self):
        self._auth_as('studenta')
        self.assertEqual(self._export('department').status_code, status.HTTP_403_FORBIDDEN)

    def test_faculty_cannot_export_the_system_report(self):
        self._auth_as('facultycs')
        self.assertEqual(self._export('system').status_code, status.HTTP_403_FORBIDDEN)

    def test_event_coordinator_cannot_export_the_system_report(self):
        self._auth_as('hodcs')
        self.assertEqual(self._export('system').status_code, status.HTTP_403_FORBIDDEN)

    def test_an_unknown_report_type_is_a_404(self):
        self._auth_as('sysadmin')
        self.assertEqual(self._export('does-not-exist').status_code, status.HTTP_404_NOT_FOUND)

    def test_a_path_traversal_report_type_is_refused(self):
        """Report type is an allowlist key, never a path component."""
        self._auth_as('sysadmin')
        for hostile in ('..', '../../etc/passwd', 'system/../system'):
            response = self.client.get(
                reverse('report-export', args=['system']).replace('system', hostile),
            )
            self.assertIn(
                response.status_code,
                (status.HTTP_404_NOT_FOUND, status.HTTP_400_BAD_REQUEST),
                hostile,
            )

    def test_an_unsupported_format_is_refused(self):
        self._auth_as('sysadmin')
        for fmt in ('exe', 'html', '../../x', 'CSV;rm -rf'):
            response = self._export('system', fmt=fmt)
            self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST, fmt)

    def test_an_empty_or_absent_format_defaults_to_csv(self):
        """`?file_format=` is indistinguishable from omitting it, and many
        clients always send the key. It means "unspecified" and falls back to
        the allowlisted default rather than erroring."""
        self._auth_as('sysadmin')
        for response in (
            self._export('system', fmt=''),
            self.client.get(reverse('report-export', args=['system'])),
        ):
            self.assertEqual(response.status_code, status.HTTP_200_OK)
            self.assertIn('text/csv', response['Content-Type'])

    def test_a_student_report_contains_only_that_student(self):
        self._auth_as('studenta')
        rows = parse_csv(self._export('student-participation').content)
        names = {row[0] for row in rows[1:]}
        self.assertEqual(names, {'studenta'})

    def test_a_student_cannot_obtain_another_students_report(self):
        self._auth_as('studenta')
        response = self._export('student-participation', params={'student': self.w.student_b.id})
        self.assertEqual(response.status_code, status.HTTP_403_FORBIDDEN)

    def test_faculty_reports_stop_at_the_department_boundary(self):
        self._auth_as('facultycs')
        rows = parse_csv(self._export('participation').content)
        names = {row[0] for row in rows[1:]}
        self.assertNotIn('studentec', names)

    def test_event_coordinator_cannot_export_another_departments_data(self):
        self._auth_as('hodcs')
        response = self._export('participation', params={'department': self.w.ec.id})
        self.assertEqual(response.status_code, status.HTTP_403_FORBIDDEN)

    def test_event_coordinator_department_report_covers_only_their_department(self):
        self._auth_as('hodcs')
        rows = parse_csv(self._export('department').content)
        names = {row[0] for row in rows[1:]}
        self.assertEqual(names, {'Computer Science'})

    def test_admin_may_export_every_type(self):
        self._auth_as('sysadmin')
        for key in registry.REPORTS:
            self.assertEqual(self._export(key).status_code, status.HTTP_200_OK, key)


class ReportFormatTests(AuthMixin, APITestCase):
    def setUp(self):
        self.w = build_world()
        self._auth_as('sysadmin')

    def _export(self, report_type='student-participation', fmt='csv'):
        response = self.client.get(reverse('report-export', args=[report_type]), {'file_format': fmt})
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        return response

    # --- CSV ---------------------------------------------------------------

    def test_csv_headers_and_rows_parse(self):
        response = self._export(fmt='csv')
        self.assertIn('text/csv', response['Content-Type'])
        rows = parse_csv(response.content)
        self.assertEqual(rows[0][0], 'Student')
        self.assertGreater(len(rows), 1)

    def test_csv_column_order_is_stable(self):
        first = parse_csv(self._export(fmt='csv').content)[0]
        second = parse_csv(self._export(fmt='csv').content)[0]
        self.assertEqual(first, second)

    # --- XLSX --------------------------------------------------------------

    def test_xlsx_opens_and_has_a_named_worksheet(self):
        response = self._export(fmt='xlsx')
        self.assertIn('spreadsheetml', response['Content-Type'])
        workbook = parse_xlsx(response.content)
        self.assertIn('Report Info', workbook.sheetnames)
        sheet = workbook[workbook.sheetnames[0]]
        self.assertEqual([c.value for c in sheet[1]][0], 'Student')
        self.assertGreater(sheet.max_row, 1)

    def test_xlsx_worksheet_name_is_within_excels_limit(self):
        for key in registry.REPORTS:
            workbook = parse_xlsx(self._export(report_type=key, fmt='xlsx').content)
            for name in workbook.sheetnames:
                self.assertLessEqual(len(name), 31, f'{key}: {name}')
                self.assertFalse(set(name) & set(':\\/?*[]'), f'{key}: {name}')

    # --- PDF ---------------------------------------------------------------

    def test_pdf_is_a_valid_document_with_readable_text(self):
        response = self._export(fmt='pdf')
        self.assertEqual(response['Content-Type'], 'application/pdf')
        self.assertTrue(response.content.startswith(b'%PDF-'))
        text = pdf_text(response.content)
        self.assertIn('Student Participation Report', text)
        self.assertIn('studenta', text)

    def test_pdf_carries_its_metadata_and_filter_summary(self):
        response = self.client.get(
            reverse('report-export', args=['student-participation']),
            {'file_format': 'pdf', 'date_from': '2020-01-01'},
        )
        text = pdf_text(response.content)
        self.assertIn('Generated by', text)
        self.assertIn('Filters', text)
        self.assertIn('from=2020-01-01', text)

    def test_every_report_type_renders_in_every_format(self):
        # 36 exports in one minute is exactly what the Phase 9 `reports`
        # throttle (20/min) exists to stop; lift it here so this test stays
        # about rendering. The throttle itself is tested in tests/.
        with mock.patch.dict('rest_framework.throttling.ScopedRateThrottle.THROTTLE_RATES', {'reports': '1000/min'}):
            for key in registry.REPORTS:
                for fmt in registry.FORMATS:
                    response = self._export(report_type=key, fmt=fmt)
                    self.assertGreater(len(response.content), 0, f'{key}/{fmt}')

    # --- headers -----------------------------------------------------------

    def test_content_disposition_carries_a_safe_filename(self):
        response = self._export(fmt='xlsx')
        disposition = response['Content-Disposition']
        self.assertTrue(disposition.startswith('attachment; filename="'))
        filename = disposition.split('"')[1]
        self.assertTrue(filename.endswith('.xlsx'))
        for bad in ('/', '\\', '..', ' '):
            self.assertNotIn(bad, filename)

    def test_reports_are_not_cacheable(self):
        response = self._export()
        self.assertIn('no-store', response['Cache-Control'])

    def test_content_length_matches_the_body(self):
        response = self._export(fmt='pdf')
        self.assertEqual(int(response['Content-Length']), len(response.content))


class EmptyReportTests(AuthMixin, APITestCase):
    """§35: an empty dataset is a valid report, not a server error."""

    def setUp(self):
        self.w = build_world()
        self._auth_as('sysadmin')

    def _empty(self, fmt):
        response = self.client.get(
            reverse('report-export', args=['student-participation']),
            {'file_format': fmt, 'date_from': '2000-01-01', 'date_to': '2000-01-02'},
        )
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        return response

    def test_empty_csv_still_has_its_header_row(self):
        rows = parse_csv(self._empty('csv').content)
        self.assertEqual(len(rows), 1)
        self.assertEqual(rows[0][0], 'Student')

    def test_empty_xlsx_still_has_its_header_row(self):
        sheet = parse_xlsx(self._empty('xlsx').content).worksheets[0]
        self.assertEqual(sheet.max_row, 1)
        self.assertEqual(sheet['A1'].value, 'Student')

    def test_empty_pdf_says_there_were_no_records(self):
        self.assertIn('No records match', pdf_text(self._empty('pdf').content))


class ReportContentSecurityTests(AuthMixin, APITestCase):
    """§38: generated files must not carry credentials or private references."""

    FORBIDDEN = ('password', 'pbkdf2', 'argon2', 'bearer ', 'refresh_token',
                 'sha256_hash', 'participation_captures', 'media/', 'jwt')

    def setUp(self):
        self.w = build_world()
        self._auth_as('sysadmin')

    def test_no_report_leaks_credentials_or_private_references(self):
        for key in registry.REPORTS:
            csv_text = self.client.get(
                reverse('report-export', args=[key]), {'file_format': 'csv'},
            ).content.decode('utf-8-sig').lower()
            for needle in self.FORBIDDEN:
                self.assertNotIn(needle, csv_text, f'{key} CSV leaked {needle!r}')

    def test_pdf_reports_carry_no_credentials(self):
        for key in ('student-participation', 'verification', 'system'):
            text = pdf_text(
                self.client.get(reverse('report-export', args=[key]), {'file_format': 'pdf'}).content,
            ).lower()
            for needle in self.FORBIDDEN:
                self.assertNotIn(needle, text, f'{key} PDF leaked {needle!r}')

    def test_the_verification_report_carries_no_capture_metadata(self):
        """Evidence hashes, coordinates and storage keys must never reach a
        report even though the underlying rows have them."""
        capture = self.w.ev_a1.current_version.captures.first()
        body = self.client.get(
            reverse('report-export', args=['verification']), {'file_format': 'csv'},
        ).content.decode('utf-8-sig')
        self.assertNotIn(capture.sha256_hash, body)
        self.assertNotIn(str(capture.latitude), body)
        self.assertNotIn(capture.object_reference.name, body)


class ReportAuditTests(AuthMixin, APITestCase):
    """§26: generation is an auditable action."""

    def setUp(self):
        self.w = build_world()

    def test_export_writes_a_report_generated_audit_entry(self):
        self._auth_as('hodcs')
        self.client.get(reverse('report-export', args=['participation']), {'file_format': 'csv'})

        entry = AuditLog.objects.filter(action='REPORT_GENERATED').first()
        self.assertIsNotNone(entry)
        self.assertEqual(entry.actor_id, self.w.event_coordinator_cs.id)
        self.assertIn('Participation Report', entry.description)
        self.assertIn('CSV', entry.description)

    def test_the_audit_entry_records_the_filter_summary_but_no_content(self):
        self._auth_as('hodcs')
        self.client.get(
            reverse('report-export', args=['participation']),
            {'file_format': 'csv', 'date_from': '2026-01-01'},
        )
        entry = AuditLog.objects.filter(action='REPORT_GENERATED').first()
        self.assertIn('from=2026-01-01', entry.description)
        self.assertNotIn('studenta', entry.description)

    def test_previewing_a_report_is_not_audited(self):
        """Only generation is a business action; previewing would make the
        trail noisy without adding traceability."""
        self._auth_as('hodcs')
        self.client.get(reverse('report-preview', args=['participation']))
        self.assertFalse(AuditLog.objects.filter(action='REPORT_GENERATED').exists())


class ReportPreviewTests(AuthMixin, APITestCase):
    def setUp(self):
        self.w = build_world()

    def test_preview_returns_the_same_rows_the_export_will_contain(self):
        self._auth_as('hodcs')
        preview = self.client.get(reverse('report-preview', args=['participation'])).data
        exported = parse_csv(
            self.client.get(
                reverse('report-export', args=['participation']), {'file_format': 'csv'},
            ).content,
        )
        self.assertEqual(preview['columns'], exported[0])
        self.assertEqual(preview['row_count'], len(exported) - 1)

    def test_preview_enforces_the_same_authorization(self):
        self._auth_as('studenta')
        self.assertEqual(
            self.client.get(reverse('report-preview', args=['system'])).status_code,
            status.HTTP_403_FORBIDDEN,
        )
